config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  resources :todos do
		collection do
			get :all
		end
	end
	resources :projects do
		collection do
			get :all
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :todos

  #def as_json options={}
	#	{
	#		title: title,
	#		todos: getTodoChildren
	#	}
	#end

	#def getTodoChildren
	#	@retValue = []
	#	todos.each do |x|
	#		@retValue.push(x.id)
	#	end
	#	return @retValue
	#end
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project

  def as_json options={}
		{
			id: id,
			text: text,
			isCompleted: isCompleted,
			projectId: project.id
		}
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @projects = Project.all
  end

  def update
    
  end

  def create

  end

  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  
  def all
    @projects = Project.all
    @todos = Todo.all
    respond_to do |format|
    format.json {render :json => {:projects => @projects,:todos => @todos}}
    end
	end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  skip_before_action :verify_authenticity_token
  def update
    #data_json = JSON.parse request.body.read
		#todo = Todo.find(data_json.id)
    todo = Todo.find(params[:id])
    todo.update(:isCompleted => !todo.isCompleted)
    redirect_to root_path
  end

  def create
    @todo = Todo.new(params.require(:todo).permit([:text, :project_id]))
    if @todo.save
			redirect_to root_path
    end
    
  end
  def all
		@todos = Todo.all
		render json: @todos
  end

  def show
    @todo = Todo.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @todo }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OblakoTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div class='header'>
  <h2>Задачи</h2>
  <a id="clickToAddTodo" href="#"><%= image_tag "addTodoIcon.png" %></a>
</div>

<div class="allProjects">
  <div class="container">
    <div class="row">
      <% @projects.each do |project| %>
        <div class="col-md-6 col-lg-4 col-12">
          <div class='oneProject'>
            <div class='projectTitle'>
              <%= project.title %>
            </div>
            <% project.todos.each do |todo| %>
              <%= form_with model: todo, method: 'PUT' do |t| %>
                <div class='todoText'>
                  <li><label> <input type="checkbox" <%= if todo.isCompleted then "checked" end %> ><label class="text"><%= todo.text %></label>  </li> </label>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div id="block">
    <h2>НОВАЯ ЗАДАЧА</h2>
    <%= form_with scope: :todo, url: todos_path, method: :post, :html => { :class => 'new_todo'} do |todo| %>
      <%= todo.text_field :text, :placeholder => "Название задачи...", :class => "todoTextField" %> <br/>
      <%= select(:todo, "project_id", @projects.collect {|p| [ p.title, p.id ] }, {prompt: "Категория"}, {:class => "select2-selection"}) %>
      <table>
        <th><%= link_to 'ОТМЕНА', "#", :class => 'cancellation' %></th>
        <th><%= link_to 'OK', "", :class => 'submit' %></th>
      </table>
    <% end %>
  </div>
</div>
<div id='bg_layer'></div>